jwt:
    key: H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B
    name: token
    expirationHours: 2
datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/internet_provider?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 1234
liquibase:
    changeLogPath: src/main/resources/db/changelog/db.changelog-master.yaml